"use client";
import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { api, token } from "../../../lib/api";
import { Shell } from "../../../components/Shell";
const transitions: Record<string, string[]> = { PENDING: ["CONFIRMED", "CANCELLED"], CONFIRMED: ["PROCESSING", "CANCELLED"], PROCESSING: ["SHIPPED", "CANCELLED"], SHIPPED: ["DELIVERED"], DELIVERED: [], CANCELLED: [] };
export default function OrderDetail() {
  const { id } = useParams<{ id: string }>(); const router = useRouter(); const [order, setOrder] = useState<any>(); const [status, setStatus] = useState(""); const [carrier, setCarrier] = useState(""); const [trackingNumber, setTrackingNumber] = useState(""); const [estimatedDeliveryDate, setEstimatedDeliveryDate] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  const load = () => api<any>(`/orders/${id}`).then((result) => { setOrder(result.order); setStatus(result.order.orderStatus); setCarrier(result.order.carrier || ""); setTrackingNumber(result.order.trackingNumber || ""); setEstimatedDeliveryDate(result.order.estimatedDeliveryDate ? new Date(result.order.estimatedDeliveryDate).toISOString().slice(0, 10) : ""); }).catch((e) => setMessage(e.message));
  useEffect(() => { if (!token()) router.push("/login"); else load(); }, [id, router]);
  async function update() { if (!confirm(`Change order status to ${status}?`)) return; setSaving(true); setMessage(""); try { await api(`/orders/${id}/status`, { method: "PATCH", body: JSON.stringify({ status, carrier, trackingNumber, estimatedDeliveryDate: estimatedDeliveryDate || undefined }) }); setMessage("Status updated."); load(); } catch (e: any) { setMessage(e.message); } finally { setSaving(false); } }
  if (!order) return <Shell><p className={message ? "error" : ""}>{message || "Loading order…"}</p></Shell>;
  const next = transitions[order.orderStatus] || []; const isShipping = status === "SHIPPED";
  return <Shell><h2>Order #{order.orderId}</h2>{message && <p className={message.includes("updated") ? "success" : "error"}>{message}</p>}<div className="grid"><section className="card"><h3>Customer</h3><p>{order.customerName}</p><p>{order.whatsappId}</p></section><section className="card"><h3>Delivery</h3><p>{order.houseBuilding}</p><p>{order.area}, {order.district}</p><p>{order.pincode}</p></section><section className="card"><h3>Product</h3><p>{order.productName} × {order.quantity}</p><p>₹{order.price} — Total ₹{order.totalAmount}</p></section><section className="card"><h3>Payment</h3><p>{order.paymentMethod} / {order.paymentStatus}</p><p>{order.razorpayPaymentId || "No verified payment ID"}</p></section></div><section className="card shipping-card"><h3>Shipping Information</h3><p>Carrier: {order.carrier || "Not available"}</p><p>Tracking number: {order.trackingNumber || "Not available"}</p><p>Shipped at: {order.shippedAt ? new Date(order.shippedAt).toLocaleString() : "Not shipped"}</p><p>Estimated delivery: {order.estimatedDeliveryDate ? new Date(order.estimatedDeliveryDate).toLocaleDateString() : "Not available"}</p><p>Delivered at: {order.deliveredAt ? new Date(order.deliveredAt).toLocaleString() : "Not delivered"}</p><p>Cancellation: {["PENDING", "CONFIRMED", "PROCESSING"].includes(order.orderStatus) ? "Available" : "Not available"}</p></section><section className="card"><h3>Order lifecycle</h3>{next.length ? <><select value={status} onChange={(e) => setStatus(e.target.value)}>{next.map((item) => <option key={item}>{item}</option>)}</select>{isShipping && <div className="shipping-fields"><label>Carrier<input value={carrier} maxLength={120} onChange={(e) => setCarrier(e.target.value)} placeholder="Optional" /></label><label>Tracking number<input value={trackingNumber} maxLength={120} onChange={(e) => setTrackingNumber(e.target.value)} placeholder="Optional" /></label><label>Estimated delivery<input type="date" value={estimatedDeliveryDate} onChange={(e) => setEstimatedDeliveryDate(e.target.value)} /></label></div>}<button className="primary" disabled={saving} onClick={update}>{saving ? "Updating…" : status === "SHIPPED" ? "Ship order" : status === "DELIVERED" ? "Mark delivered" : status === "CANCELLED" ? "Cancel order" : "Update status"}</button></> : <p className="muted">This order has reached a final lifecycle state.</p>}<p className="muted">Created {new Date(order.createdAt).toLocaleString()} · Updated {new Date(order.updatedAt).toLocaleString()}</p></section></Shell>;
}
